project:
  type: website

website:
  title: "Richard Wen"
  navbar:
    right:
      - blog.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/richardwen/
      - icon: github
        href: https://github.com/rrwen
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css

output-dir: "."

