project:
  type: website
  output-dir: docs

website:
  title: "Richard Wen"
  navbar:
    left:
    - projects.qmd
    - blog.qmd
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/richardwen/
      - icon: github
        href: https://github.com/rrwen
  search: false

format:
  html:
    theme:
      - cosmo
      - brand
    css: css/styles.css
